name: Build Html Report

on:
  push:
  workflow_dispatch:

jobs:
  build-report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - uses: actions/checkout@v3
      - name: Checkout web5-spec repo
        uses: actions/checkout@v3
        with:
          repository: TBD54566975/web5-spec
          path: web5-spec
      - name: Checkout tbdex repo
        uses: actions/checkout@v3
        with:
          repository: TBD54566975/tbdex
          path: tbdex
      - name: Copy web5-spec test-vectors
        run: cp -r web5-spec/test-vectors ./test-vectors
      - name: Copy tbdex hosted test-vectors
        run: cp -r tbdex/hosted/test-vectors ./tbdex-test-vectors
      - uses: actions/setup-go@v4
      - name: build html
        run: |
          cd reports
          go run ./cmd/build-html
          cp -r ./static/* _site
          mv _site ../
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CICD_ROBOT_GITHUB_APP_NAME: ${{ secrets.CICD_ROBOT_GITHUB_APP_NAME }}
          CICD_ROBOT_GITHUB_APP_PRIVATE_KEY: ${{ secrets.CICD_ROBOT_GITHUB_APP_PRIVATE_KEY }}
          CICD_ROBOT_GITHUB_APP_ID: ${{ secrets.CICD_ROBOT_GITHUB_APP_ID }}
          CICD_ROBOT_GITHUB_APP_INSTALLATION_ID: ${{ secrets.CICD_ROBOT_GITHUB_APP_INSTALLATION_ID }}
      - uses: actions/upload-pages-artifact@v2
      - name: deploy GitHub Pages
        uses: actions/deploy-pages@v3
        if: github.ref == 'refs/heads/main'
